### ISSUE TITLE
Standardize column name arguments

### ISSUE THREAD

**Issue by steffilazerte** [ARUtools/ARUtools#15]
Go back and standardize the functions so that we...

- use character arguments where referring to column names that do not exist in data being supplied to the function (e.g., columns are in a data file, or will be created by the function internally). 
- use NSE when referring to column names that are supplied at the same time as the data they belong to.

**Comment by steffilazerte** [comment]
@dhope I'm starting on this next and am trying to come up with a sensible way forward. 

Some of the functions use character column references which I think make sense to leaves as character (because they're complex and more than just referring to a column in a data frame). For the others which are more straight forward, I think NSE makes sense, because it's just about picking the column from an existing data frame. 

So for the following main functions, this is what we have and what I propose to do:

### Metadata cleaning

function | column ref in arguments | suggested approach
--- | --- | ---------
`clean_site_index()` | Column refs that refer to either a data frame OR a file on disk.<br>Some are also multi-part (i.e., `col_coords = c("longitude", "latitude")`) | Leave these as character: <br>a) Doesn't make sense to have multi-part NSE column refs (would have to re-write those as separate arguments)<br>b) doesn't necessarily refer to a data frame (would have to adapt the workflow to transform to character if a file name)
`clean_gps()` | None |
`clean_metadata()` | None |
`add_sites()` | `by = ` column refs, which make sense to leave as character (cf `left_join()` etc.) | Leave as character
`calc_sun()` | None |

### Selections

function | column ref in arguments  | suggested approach
---------- | --------------- | ----
`sim_selection_weights()` | None |
`cal_selection_weights()` | Basic column refs for site_id, min and date | Use NSE
`sample_recording()` | Basic column refs for site_id, and selection weights | Use NSE (already implemented)

### Other
function | column ref in arguments  | suggested approach
---------- | --------------- | -------
`clip_wave_single()` | Basic column refs for various columns | Use NSE
`clip_wave()` | Basic column refs for various columns | Use NSE
`get_wav_length()` | None |
`sox_spectro()` | None |
`acoustic_indices()` | None |
`add_wildtrax()` | None |
`check_file()` | None |
`check_problems()` | None |
`check_meta()` | None |
`count_files()` | None |
`create_dirs()` | None |
`create_pattern_XXX()` | None |

## Questions
- Does this make sense?
- Right now all column arguments are called `col_XXX`... I think we should distinguish between those that require an NSE column and those that require a character one
  - we could use `col_XXX` for NSE
  - we could use `name_XXX` for character? So in `clean_site_index()`, we would have `name_aru_id` `name_site_id`, etc. which would parallel the `pattern_site_id` and the `col_site_id` used in other functions

**Comment by dhope** [comment]
Wow! This is a great table to sort this out. This looks like the right approach. The only thought I had was for the by columns is the move towards NSE with the `dplyr::join_by` function. However, I don't think it is widely used, so I suspect this is the right approach for `add_sites`.


I think your proposed naming conventions for variables makes sense and would allow learning to be fairly straightforward if it is added to the "Getting Started" vignette.

**Comment by steffilazerte** [comment]
Thanks for the feedback, I'll get started on that then! Also your mentioning of `join_by`() reminded me that that would be a good thing to implement in `add_sites()`. Right now, we do it 'by hand' but I think it would be cleaner to use `join_by()`, I'll open a new issue to remind us, but will leave it for last.

**Comment by steffilazerte** [comment]
Okay, one last gnarly bit with `clip_wave()`, currently we have the option for `col_subdir_out` to be a vector of column names. 
However, given my level of expertise with NSE in column names, I think we're going to have to pick a different approach (I've never seen an example of NSE column names referred to in anything other than named arguments or `...`, never a list or vector).

1. Easiest is to just say that the `col_subdir_out` can only refer to a single column, and if there are subdirectories to be made, then they're made in paths contained in that column (i.e. "test1/a", "test1/b", etc.)
2. Alternatively we could supply a second `col_subsubdir_out` which is NULL by default
3. We could add ... and insist that we only take extra items named as `col_subsubdir_out` `col_subsubsubdir_out`
4. We drop NSE for the column names on this function.

My preferences is for number 1. I think madness lies down the paths of 2 and 3, and 4 seems like a shame, just for one argument.

@dhope Thoughts?

**Comment by dhope** [comment]
Below is an example from `dplyr` using NSE of column names in a vector. That said, I'm not sure it is super important for this function. I don't think 1 is the appropriate solution given my previous use of the variable, but I also think option 4 (which I believe is what it is now) is maybe the simplest solution for now and I we can move this to a new issue as an enhancement.


``` r
palmerpenguins::penguins |> dplyr::summarise(n=dplyr::n(), .by = c(species, year))
#> # A tibble: 9 × 3
#>   species    year     n
#>   <fct>     <int> <int>
#> 1 Adelie     2007    50
#> 2 Adelie     2008    50
#> 3 Adelie     2009    52
#> 4 Gentoo     2007    34
#> 5 Gentoo     2008    46
#> 6 Gentoo     2009    44
#> 7 Chinstrap  2007    26
#> 8 Chinstrap  2008    18
#> 9 Chinstrap  2009    24
```

<sup>Created on 2024-03-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by dhope** [comment]
One difference between my use cases and the above example is that order matters, so perhaps your solution #1 is a safer route to take.

**Comment by steffilazerte** [comment]
Okay, it isn't my most elegant work, but we have NSE names for everywhere we discussed, and even the really annoying c() arguments. 
We also still have good error messages (dplyr does it by using the tidyselect pacakge, which we could do, but doesn't give us quite as comprehensive an error messages as we had in the first iteration). 
Whew!

(Work in fb8298b8, I just forget the reference)
