### ISSUE TITLE
sample_recordings() - previously fun_aru_samp

### ISSUE THREAD

**Issue by steffilazerte** [ARUtools/ARUtools#23]
This issue pertains to refactoring the function `fun_aru_samp()` to `sample_recordings()`

- Generally, I've applied the same changes as those made to [`BASSr::run_grts_on_BASS()`](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/BASS_studyArea_analysis.R#L58)
- I've started using NSE for the column names (and will continue when I deal with #15)
- Added tests
- Added examples
- Works with spatial or non-spatial data

**Comment by steffilazerte** [comment]
Ah, hmm, I just realized that the original doesn't use real spatial data, but doy and t2sr/t2ss... whoops, I'll have to adjust that!

**Comment by dhope** [comment]
Yes, good catch. I can't think of a reasonable use case to modify them between weighting and selection.
