### ISSUE TITLE
Pull timezone from BAR ARU sound file names

### ISSUE THREAD

**Issue by steffilazerte** [ARUtools/ARUtools#27]
**Is your feature request related to a problem? Please describe.**
Supplying timezones used in ARU setup

**Describe the solution you'd like**
Instead of having to supply the timezone manually, it could be detected from the BAR ARU sound file names.

**Comment by dhope** [comment]
Closing this with 1f0f8f21ba83edbbd10961203e145efb97dbfeb5. Now can create patterns using `create_pattern_tz_offset()` for use in `clean_meatadata()`, which will return a new column `tz_offset`. 

Decided not to push this further for datetime estimation as it could introduce errors and is only used in BARLT ARUs.
