### ISSUE TITLE
clean_logs()

### ISSUE THREAD

**Issue by steffilazerte** [ARUtools/ARUtools#28]
This issue is to discuss the new function `clean_logs()`.

**Comment by steffilazerte** [comment]
We have a new function called `clean_logs()` which cleans the BARLT log files (e.g., `logfile_00010962_SD1.txt`) 🎉 

You can return all data, or just the gps, or just recording data. Here's a quick example with all data:
```
> log_files <- "../ARUtools - Extra/aru_log_files/P028/1A_BARLT10962/logfile_00010962_SD1.txt"
> clean_logs(log_files)
# A tibble: 1,287 × 17
   file_name   path event     date_time             lat   lon rec_file    rec_size rec_end             schedule_date schedule_name
   <fs::path> <int> <chr>     <dttm>              <dbl> <dbl> <chr>       <chr>    <dttm>              <date>        <chr>        
 1 1              1 gps       2022-03-18 09:29:29  50.3 -85.4 NA          NA       NA                  2022-03-12    Nakina2022   
 2 1              1 recording 2022-05-01 20:30:00  NA    NA   0:/2022050… 0 MB     2022-05-01 20:29:29 2022-03-12    Nakina2022   
 3 1              1 recording 2022-05-01 20:30:00  NA    NA   0:/2022050… 0 MB     2022-05-01 20:35:00 2022-03-12    Nakina2022   
 4 1              1 gps       2022-05-01 20:30:35  50.3 -85.4 NA          NA       NA                  2022-03-12    Nakina2022   
 5 1              1 recording 2022-05-01 21:00:00  NA    NA   0:/2022050… 50 MB    2022-05-01 21:05:00 2022-03-12    Nakina2022   
 6 1              1 recording 2022-05-01 21:30:00  NA    NA   0:/2022050… 50 MB    2022-05-01 21:35:00 2022-03-12    Nakina2022   
 7 1              1 recording 2022-05-01 22:00:00  NA    NA   0:/2022050… 50 MB    2022-05-01 22:05:00 2022-03-12    Nakina2022   
 8 1              1 recording 2022-05-01 22:30:00  NA    NA   0:/2022050… 50 MB    2022-05-01 22:35:00 2022-03-12    Nakina2022   
 9 1              1 recording 2022-05-01 23:00:00  NA    NA   0:/2022050… 50 MB    2022-05-01 23:05:00 2022-03-12    Nakina2022   
10 1              1 recording 2022-05-01 23:30:00  NA    NA   0:/2022050… 50 MB    2022-05-01 23:35:00 2022-03-12    Nakina2022   
# ℹ 1,277 more rows
# ℹ 6 more variables: schedule_lat <dbl>, schedule_lon <dbl>, schedule_sr <chr>, schedule_ss <chr>, meta_serial <chr>,
#   meta_firmware <chr>
# ℹ Use `print(n = ...)` to see more rows
```




First, note that I commented out the older read log functions, but they're still there in the renamed `clean_logs.R` script.

Second, there are tests and examples, but I cheated a bit. It's hard to test the functionality of a log file without a real log file so the tests require that you have the example log files you shared with me available (otherwise it's skipped). So it's there and can be checked locally, but wouldn't be run on GitHub through CI. However, we could always include an example log file if you have one you don't mind including publicly.

Finally, this works for BARLT log files but not for others. However, if I've understood correctly, the others are already available via the `clean_gps()` function, right? That function should be returning all the GPS data in each file.

Other log files I have are almost exclusively GPS-only data: 

**`Reclog.csv`**
- Could extract microphone details?
```
Recording log
Date (DD/MM/YYYY),Time (HH:MM:SS),UTC Timezone,Filename,Gain (dB),Battery Voltage,% full,Charger status,Card slot #,CID,Free space,Capacity,Microphone serial #,Microphone type,Microphone date of manufacture,
29/05/2021 ,21:13:00 ,-04:00,0:/20210529_NapkenLk_duskdawn/20210529T211300-0400_SS.wav,40dB,40dB,4.15V,96%,,1,0x035344534331323880ED8B0E6B014BA7,119GB,119GB,003130,STD AUDIO MIC,29/07/2019 ,
29/05/2021 ,21:43:00 ,-04:00,0:/20210529_NapkenLk_duskdawn/20210529T214300-0400_SS.wav,40dB,40dB,4.15V,96%,,1,0x035344534331323880ED8B0E6B014BA7,118.9GB,119GB,003130,STD AUDIO MIC,29/07/2019 ,
29/05/2021 ,22:13:00 ,-04:00,0:/20210529_NapkenLk_duskdawn/20210529T221300-0400_SS.wav,40dB,40dB,4.15V,96%,,1,0x035344534331323880ED8B0E6B014BA7,118.9GB,119GB,003130,STD AUDIO MIC,29/07/2019 ,
29/05/2021 ,22:43:00 ,-04:00,0:/20210529_NapkenLk_duskdawn/20210529T224300-0400_SS.wav,40dB,40dB,4.14V,96%,,1,0x035344534331323880ED8B0E6B014BA7,118.8GB,119GB,003130,STD AUDIO MIC,29/07/2019 ,
29/05/2021 ,23:13:00 ,-04:00,0:/20210529_NapkenLk_duskdawn/20210529T231300-0400_SS.wav,40dB,40dB,4.14V,96%,,1,0x035344534331323880ED8B0E6B014BA7,118.8GB,119GB,003130,STD AUDIO MIC,29/07/2019 ,
```
**`GPS_log.csv`** 
- Strictly gps lat/lon data per date, no metadata
```
GPS log file
Latitude (decimal degrees),Longitude (decimal degrees),HH/MM,DD/MM/YY
+45.3500,-076.0104,13:15,09/05/2021
+52.3924,-085.6370,17:23,03/06/2021
```

Or were there other types of log files from which I was supposed to extract more metadata? If so, we can expand on this function to read other log files and include extra metadata as required, but if that's not a priority, I'd prefer to wait as I'm out of hours.

What do you think?

**Comment by dhope** [comment]
Very cool! Thanks this is great. Yes, the SM logs are read by the `clean_gps()`, so this is a great addition.

**Comment by dhope** [comment]
I'm going to re-open for myself as I want to see if there are some additional features folks would like added.

**Comment by dhope** [comment]
Closing this for now as I think this is in a good position for basic functionality. I've opened a new Issue #42 for future expansion.
