### ISSUE TITLE
format_clip_wave() family 

### ISSUE THREAD

**Issue by steffilazerte** [ARUtools/ARUtools#8]
Hi @dhope, going through the format_clip_wave functions, I have a couple of questions about changes I'd like to make:

1. Can I rename these to `clip_wave()` and `clip_wave_single()`? They aren't *really* formatted, although the names are for sure. Or perhaps `fmt_clip_wave()`? Just to keep things a bit shorter
2. I've been thinking about the `warn` option. It is good to warn the user about potentially overwriting, but making that interactive a) is slow b) doesn't work in a non-interactive script. 
    - What about using an `overwrite` option instead of the `warn` option?
    - This will check if the files exist and stop if they do and `overwrite = FALSE`. It's still a check, but will work all the time and is a bit quicker.
    - We could also add a `dry_run` option (i.e tell me what you are going to move and where), to double check things. Together these should be equally safe, but also faster which fewer interruptions.
3. I saw in your processing scripts that you create the folders first, but is there any reason not to create the folders when running the function itself? That will save you a step and will also make it easier to match the file paths together. 
4. Is there any reason that you would need both `in_base_directory` and `filepath_in_col`? Shouldn't we just insist that the file names in the `filepath_in_col` are either absolute or relative to the current working directory? Or is that problematic?
   - If it is occasionally problematic, but not often, we could leave it up to the user to fix the file names before running the function
   - If it always problematic, we can deal with it in the function 😄

**Comment by steffilazerte** [comment]
Hi @dhope, I'm just finishing up the clip_wave() family of functions, and have one last question.
Is there any reason to have the job::job() code inside the function, rather than outside?

ie. `clip_wave(..., use_job = TRUE)` vs. `job::job(clip_wave(...))`

If not, I would suggest leaving it up to the user to wrap the function in `job::job()`?

**Comment by dhope** [comment]
Sorry I missed this last comment from you @steffilazerte here. Let's leave as is (with option for `job`) for now, but I think you might be right that it is unnecessary and adds dependencies we could remove. I'll put this in a separate issue so I don't forget.
