### ISSUE TITLE
wave lengths - sox vs. tuneR

### ISSUE THREAD

**Issue by steffilazerte** [ARUtools/ARUtools#9]
If reading the wave lengths in `clip_wave()` is time consuming via tuneR, consider using Sox (command line tool, generally much faster than most R sound packages). 

Something like:
`system("sox --i -D file.wav")`

I don't actually know if this is a problem (speed-wise), but making this note as a reminder of an alternative if it turns out to be a problem.

**Comment by dhope** [comment]
Interesting. Thanks for this. I've held off using the sox program (though it is in the soxSpectogram function) because it requires users to download another program, and I suspect most users won't. However, I'll test it out and if it saves a lot of time, it is worth considering as an option.

**Comment by steffilazerte** [comment]
Yes, and you could always keep the existing functionality with an argument for users who couldn't/didn't want to install SoX.

**Comment by dhope** [comment]
Closing this as for my system anyway, it appears sox is much slower.

``` r
f <- "D:/!TMP_2024_Zoom/2024-06-11/240610-062301.WAV"

suppressWarnings(
b <- 
bench::mark(
  system(glue::glue("sox --i -D {f}")),
  ARUtools::get_wav_length(f, return_numeric = TRUE), check = F
  )
)

b
#> # A tibble: 2 × 6
#>   expression                             min median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                          <bch:> <bch:>     <dbl> <bch:byt>    <dbl>
#> 1 "system(glue::glue(\"sox --i -D {f… 39.1ms   45ms      22.2        0B      0  
#> 2 "ARUtools::get_wav_length(f, retur… 18.4ms 20.3ms      49.4    8.58MB     41.8
```

<sup>Created on 2024-09-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
